### ISSUE TITLE
Validation failed: active is not defined in blueprints

### ISSUE THREAD

**Issue by xchardon** [bit-it/grav-facebook-feed#2]
Hi, I get this error anytime I save the configuration page:
`Validation failed: active is not defined in blueprints`

A workaround is to use "validation: loose" (instead of strict) in blueprints.yaml
I tried removing line "active: true" in file facebook-feed.yaml, but it did not solve the problem

best regards

**Comment by bjoernbohr** [comment]
sorry for the late reply. I#ll will have a look into that.
